# Generated by Django 3.1.7 on 2021-04-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210406_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='descr',
            field=models.TextField(default='No description for this plane'),
        ),
    ]
